'use strict';
const REAL_VIDEO_FILES=['01-projektstart.mp4','02-grundstueck.mp4','03-vermessung.mp4','04-vorprojekt.mp4','05-ausfuehrungsplanung.mp4','06-baustelleneinrichtung.mp4','07-absteckung.mp4','08-aushub-baugrube.mp4','09-planum-unterbau.mp4','10-werkleitungen.mp4','11-fundation.mp4','12-bodenplatte.mp4','13-untergeschoss.mp4','14-waende-stuetzen.mp4','15-geschossdecken.mp4','16-dach.mp4','17-fenster-fassade.mp4','18-sanitaer-rohinstallation.mp4','19-innenwaende-vorwand.mp4','20-bodenaufbau.mp4','21-sanitaer-endmontage.mp4','22-umgebung-entwaesserung.mp4','23-pruefung-inbetriebnahme.mp4','24-uebergabe-betrieb.mp4'];
let videoSeeking=false;
const baseOpenLesson=openLesson,baseShowStep=showStep;
function activeLessonVideo(){return document.getElementById('lessonVideo')}
function videoStepStart(i,v){return v.duration?v.duration*i/4:0}
function paintVideoProgress(){const v=activeLessonVideo();if(!v||!v.duration)return;const s=Math.min(3.9999,Math.max(0,v.currentTime/v.duration*4)),n=Math.floor(s);if(n!==stepIndex){stepIndex=n;stepMarkup()}stepProgress=s-n;$('animationScrub').value=String(Math.round(stepProgress*1000));syncStepState();updateLiveText();$('animationStatus').textContent=v.paused?'Ansicht':'Läuft · '+(stepIndex+1)+'/4'}
function mountLessonVideo(){const l=LESSONS[lessonIndex],stage=$('diagramStage'),file=REAL_VIDEO_FILES[lessonIndex];stage.className='diagramStage videoStage is-loading';stage.innerHTML='<video id="lessonVideo" class="lessonVideo" muted playsinline preload="metadata" aria-label="Reale Baustellenaufnahme: '+esc(l.title)+'"><source src="videos/'+file+'" type="video/mp4"></video><div class="videoShade"><span class="videoCaption">'+esc(l.title)+'</span></div>';const v=activeLessonVideo();v.addEventListener('loadedmetadata',()=>{stage.classList.remove('is-loading');v.currentTime=videoStepStart(stepIndex,v);paintVideoProgress()},{once:true});v.addEventListener('timeupdate',()=>{if(!videoSeeking)paintVideoProgress()});v.addEventListener('ended',()=>{playingAll=false;setPlaying(false);$('animationStatus').textContent='Fertig'});v.addEventListener('error',()=>{stage.classList.remove('is-loading');stage.classList.add('has-error')});$('zoomDiagram').textContent='Vollbild ↗';$('zoomDiagram').setAttribute('aria-label','Video im Vollbild zeigen');$('diagramNote').textContent='Reale, geschnittene Baustellenaufnahme. Die vier Lernschritte springen gezielt durch den Clip; der Erklärungstext ordnet das sichtbare Geschehen fachlich ein.';const top=document.querySelector('.visualTop');if(top&&!top.querySelector('.footageTag'))top.insertAdjacentHTML('afterbegin','<span class="footageTag">Reale Aufnahme</span>')}
openLesson=function(index,scroll=false,writeHistory=true){baseOpenLesson(index,scroll,writeHistory);mountLessonVideo()};
showStep=function(index,manual=true){baseShowStep(index,manual);stepProgress=0;const v=activeLessonVideo();if(v&&v.duration){videoSeeking=true;v.currentTime=videoStepStart(stepIndex,v)+.01;videoSeeking=false}$('animationScrub').value='0';syncStepState();updateLiveText()};
updateVisual=function(){const v=activeLessonVideo();if(v&&v.duration&&!playing){const t=v.duration*(stepIndex+stepProgress)/4;if(Math.abs(v.currentTime-t)>.06){videoSeeking=true;v.currentTime=t;videoSeeking=false}}$('animationScrub').value=String(Math.round(stepProgress*1000));syncStepState();updateLiveText()};
setPlaying=function(value){const v=activeLessonVideo();playing=Boolean(value&&v);if(!playing)playingAll=false;if(frameId)cancelAnimationFrame(frameId);frameId=0;$('playLesson').textContent=playing?'Ⅱ Pause':'▶ Video abspielen';$('playLesson').setAttribute('aria-pressed',String(playing));syncStepState();updateLiveText();if(!v)return;v.playbackRate=({slow:.75,normal:1,fast:1.25}[$('lessonSpeed').value]||1);if(playing){$('animationStatus').textContent='Läuft · '+(stepIndex+1)+'/4';v.play().catch(()=>{playing=false;syncStepState()})}else v.pause()};
startStep=function(restart=false){const v=activeLessonVideo();if(!v)return;if(restart||v.ended){stepIndex=0;stepProgress=0;v.currentTime=0;stepMarkup()}else if(stepProgress>=.99)v.currentTime=videoStepStart(stepIndex,v);playingAll=true;setPlaying(true)};
openDiagramZoom=function(){const v=activeLessonVideo();if(!v)return;if(v.requestFullscreen)v.requestFullscreen();else if(v.webkitEnterFullscreen)v.webkitEnterFullscreen()};
$('lessonSpeed').addEventListener('change',()=>{const v=activeLessonVideo();if(v)v.playbackRate=({slow:.75,normal:1,fast:1.25}[$('lessonSpeed').value]||1)});$('playLesson').textContent='▶ Video abspielen';$('replayLesson').setAttribute('aria-label','Video von vorn abspielen');$('appVersion').textContent='Version 15 · Realvideo';document.querySelector('.stepHint').textContent='Das Video ist in vier Lernabschnitte gegliedert. Mit Pause und Regler kannst du jeden Arbeitsgang genau betrachten.';mountLessonVideo();
